jdbc.url=jdbc:postgresql://postgres:5432/certain_db
jdbc.user=postgres
jdbc.password=postgres
jdbc.driver=org.postgresql.Driver

ontop.mapping=/opt/ontop/input/mapping.ttl
ontop.ontology=/opt/ontop/input/ontology.ttl
