"""refine the schema new

Revision ID: 0a178b606ca3
Revises: 7c6294968683
Create Date: 2025-12-19 16:28:51.809166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a178b606ca3'
down_revision: Union[str, None] = '7c6294968683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('experiment_stage', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'experiment_stage')
    # ### end Alembic commands ###
