"""change timestamp type start_end_time

Revision ID: 34854eb80257
Revises: 3b554c96e0af
Create Date: 2025-07-21 18:56:27.169114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34854eb80257'
down_revision: Union[str, None] = '3b554c96e0af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkpoints', 'creation_time',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('data', 'creation_time',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('data', 'last_update_time',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('data_metrics', 'timestamp',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('data_resources', 'timestamp',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('drift_metrics', 'timestamp',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('examples', 'timestamp',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('experiments', 'creation_time',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('experiments', 'last_update_time',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('last_model_metrics', 'timestamp',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('model_architecture', 'creation_time',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('model_metrics', 'timestamp',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('resources', 'timestamp',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('runs_logs', 'log_creation_time',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('weight_distribution', 'timestamp',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weight_distribution', 'timestamp',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('runs_logs', 'log_creation_time',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('resources', 'timestamp',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('model_metrics', 'timestamp',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('model_architecture', 'creation_time',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('last_model_metrics', 'timestamp',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('experiments', 'last_update_time',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('experiments', 'creation_time',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('examples', 'timestamp',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('drift_metrics', 'timestamp',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('data_resources', 'timestamp',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('data_metrics', 'timestamp',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('data', 'last_update_time',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('data', 'creation_time',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('checkpoints', 'creation_time',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
