"""Fix nullable values

Revision ID: 390dfe781f3a
Revises: 863097e14f7c
Create Date: 2025-04-29 16:21:58.478658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '390dfe781f3a'
down_revision: Union[str, None] = '863097e14f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkpoints', 'checkpoint_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('checkpoints', 'checkpoint_location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('data', 'data_stage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('data', 'data_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('data', 'data_source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('data', 'data_version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('data', 'data_location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('data', 'data_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('data', 'data_format',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('data_hyperparameters', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('data_metrics', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('data_metrics', 'data_stage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('data_metrics', 'is_NaN',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('data_resources', 'stage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('data_resources', 'value',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('data_techniques', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('last_model_metrics', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('last_model_metrics', 'step',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('last_model_metrics', 'stage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('last_model_metrics', 'is_NaN',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('model_architecture', 'architecture_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('model_architecture', 'activation_function',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('model_architecture', 'loss_function',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('model_architecture', 'optimizer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('model_architecture', 'layer_structure',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('model_architecture', 'framework',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('model_architecture', 'metrics',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('model_architecture', 'input_shape',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('model_architecture', 'output_shape',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('model_architecture', 'number_of_layers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('model_architecture', 'number_of_total_parameters',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('model_architecture', 'number_of_trainable_parameters',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('model_architecture', 'nummber_of_non_trainable_parameters',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('model_deployed', 'model_version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('model_hyperparameters', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('runs', 'run_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('runs', 'source_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('runs', 'source_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('runs', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('runs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('runs', 'source_version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('runs_code', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('runs_logs', 'log_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('runs_logs', 'log_message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runs_logs', 'log_message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('runs_logs', 'log_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('runs_code', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('runs', 'source_version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('runs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('runs', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('runs', 'source_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('runs', 'source_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('runs', 'run_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('model_hyperparameters', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('model_deployed', 'model_version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('model_architecture', 'nummber_of_non_trainable_parameters',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('model_architecture', 'number_of_trainable_parameters',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('model_architecture', 'number_of_total_parameters',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('model_architecture', 'number_of_layers',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('model_architecture', 'output_shape',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('model_architecture', 'input_shape',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('model_architecture', 'metrics',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('model_architecture', 'framework',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('model_architecture', 'layer_structure',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('model_architecture', 'optimizer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('model_architecture', 'loss_function',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('model_architecture', 'activation_function',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('model_architecture', 'architecture_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('last_model_metrics', 'is_NaN',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('last_model_metrics', 'stage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('last_model_metrics', 'step',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('last_model_metrics', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('data_techniques', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('data_resources', 'value',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('data_resources', 'stage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('data_metrics', 'is_NaN',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('data_metrics', 'data_stage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('data_metrics', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('data_hyperparameters', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('data', 'data_format',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('data', 'data_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('data', 'data_location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('data', 'data_version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('data', 'data_source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('data', 'data_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('data', 'data_stage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('checkpoints', 'checkpoint_location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('checkpoints', 'checkpoint_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
