"""run start_end_time

Revision ID: 398326837757
Revises: 645bab0e3cc1
Create Date: 2025-07-21 18:41:01.710982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '398326837757'
down_revision: Union[str, None] = '645bab0e3cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runs', 'start_time',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('runs', 'end_time',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runs', 'end_time',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('runs', 'start_time',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
