"""update standards table to have primary keys

Revision ID: 415ac7e1864b
Revises: c6ef07767135
Create Date: 2026-08-21 13:33:05.631131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '415ac7e1864b'
down_revision: Union[str, None] = 'c6ef07767135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # create a composite primary key on standards table
    op.create_primary_key(
        "pk_standards",
        "standards",
        ["standard_id", "model_id", "run_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # drop the composite primary key created in upgrade
    op.drop_constraint("pk_standards", "standards", type_="primary")
    # ### end Alembic commands ###
