"""update database schema

Revision ID: 54d2069b728a
Revises: 4628dcda3b22
Create Date: 2026-08-14 10:22:20.591862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54d2069b728a'
down_revision: Union[str, None] = '4628dcda3b22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('declaration_of_conformity', sa.Column('deployment_id', sa.String(), nullable=True))
    op.add_column('explainable_ai_features', sa.Column('deployment_id', sa.String(), nullable=True))
    op.add_column('human_oversight_mechanisms', sa.Column('deployment_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('human_oversight_mechanisms', 'deployment_id')
    op.drop_column('explainable_ai_features', 'deployment_id')
    op.drop_column('declaration_of_conformity', 'deployment_id')
    # ### end Alembic commands ###
