"""update database schema

Revision ID: 5888e6450d09
Revises: bd3f30a900af
Create Date: 2026-08-12 17:41:33.227524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5888e6450d09'
down_revision: Union[str, None] = 'bd3f30a900af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_actors', 'run_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('ai_actors_experiment_id_fkey'), 'ai_actors', type_='foreignkey')
    op.drop_column('ai_actors', 'experiment_id')
    op.add_column('data_techniques', sa.Column('technique_details', sa.JSON(), nullable=True))
    op.add_column('runtime_environment', sa.Column('details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runtime_environment', 'details')
    op.drop_column('data_techniques', 'technique_details')
    op.add_column('ai_actors', sa.Column('experiment_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('ai_actors_experiment_id_fkey'), 'ai_actors', 'experiments', ['experiment_id'], ['experiment_id'])
    op.alter_column('ai_actors', 'run_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
