"""fix runtime_env table

Revision ID: 6113f5db0bfb
Revises: f2eacbdb30d4
Create Date: 2026-08-17 12:51:25.179461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6113f5db0bfb'
down_revision: Union[str, None] = 'f2eacbdb30d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runtime_environment', sa.Column('run_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'runtime_environment', 'runs', ['run_id'], ['run_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runtime_environment', type_='foreignkey')
    op.drop_column('runtime_environment', 'run_id')
    # ### end Alembic commands ###
