"""add_change_log_table

Revision ID: 632582f15496
Revises: 0a178b606ca3
Create Date: 2025-12-23 10:19:26.159967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '632582f15496'
down_revision: Union[str, None] = '0a178b606ca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_logs',
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('change_description', sa.String(), nullable=False),
    sa.Column('changed_by', sa.String(), nullable=False),
    sa.Column('change_timestamp', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('log_id', 'run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_logs')
    # ### end Alembic commands ###
