"""update standard database table

Revision ID: 63b26ad2ae62
Revises: merge_6a714eb__9f1c2d3b4a5e
Create Date: 2026-08-14 15:45:59.549578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63b26ad2ae62'
down_revision: Union[str, None] = 'merge_6a714eb__9f1c2d3b4a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standards', sa.Column('run_id', sa.String(), nullable=False))
    op.add_column('standards', sa.Column('filename', sa.String(), nullable=False))
    op.add_column('standards', sa.Column('file_type', sa.String(), nullable=False))
    op.add_column('standards', sa.Column('mime_type', sa.String(), nullable=False))
    op.add_column('standards', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('standards', sa.Column('link_to_artifacts', sa.String(), nullable=True))
    op.add_column('standards', sa.Column('creation_time', sa.Numeric(), nullable=False))
    op.drop_constraint(op.f('standards_experiment_id_deployment_id_model_id_fkey'), 'standards', type_='foreignkey')
    op.create_foreign_key(None, 'standards', 'runs', ['run_id'], ['run_id'])
    op.drop_column('standards', 'model_id')
    op.drop_column('standards', 'publication_date')
    op.drop_column('standards', 'name')
    op.drop_column('standards', 'experiment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standards', sa.Column('experiment_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('standards', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('standards', sa.Column('publication_date', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('standards', sa.Column('model_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'standards', type_='foreignkey')
    op.create_foreign_key(op.f('standards_experiment_id_deployment_id_model_id_fkey'), 'standards', 'model_deployed', ['experiment_id', 'deployment_id', 'model_id'], ['experiment_id', 'deployment_id', 'model_id'])
    op.drop_column('standards', 'creation_time')
    op.drop_column('standards', 'link_to_artifacts')
    op.drop_column('standards', 'file_size')
    op.drop_column('standards', 'mime_type')
    op.drop_column('standards', 'file_type')
    op.drop_column('standards', 'filename')
    op.drop_column('standards', 'run_id')
    # ### end Alembic commands ###
