"""Fix the runCode table adding some more info

Revision ID: 6a55889a3f39
Revises: 26a225857289
Create Date: 2026-06-30 10:01:08.784920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a55889a3f39'
down_revision: Union[str, None] = '26a225857289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs_code', sa.Column('git_commit_short', sa.String(), nullable=False))
    op.add_column('runs_code', sa.Column('git_branch', sa.String(), nullable=False))
    op.add_column('runs_code', sa.Column('git_message', sa.String(), nullable=False))
    op.add_column('runs_code', sa.Column('git_author', sa.String(), nullable=False))
    op.add_column('runs_code', sa.Column('git_author_email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs_code', 'git_author_email')
    op.drop_column('runs_code', 'git_author')
    op.drop_column('runs_code', 'git_message')
    op.drop_column('runs_code', 'git_branch')
    op.drop_column('runs_code', 'git_commit_short')
    # ### end Alembic commands ###
