"""update database schema nothing

Revision ID: 6a714eb887eb
Revises: 38521158cbb7
Create Date: 2026-08-14 15:12:36.162728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a714eb887eb'
down_revision: Union[str, None] = '38521158cbb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('standards', 'deployment_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('standards', 'deployment_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
