"""update interfaces

Revision ID: 6ce70ae22ea9
Revises: 6113f5db0bfb
Create Date: 2026-08-17 21:57:20.810514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ce70ae22ea9'
down_revision: Union[str, None] = '6113f5db0bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interfaces', sa.Column('run_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'interfaces', 'runs', ['run_id'], ['run_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interfaces', type_='foreignkey')
    op.drop_column('interfaces', 'run_id')
    # ### end Alembic commands ###
