"""refine the schema

Revision ID: 7c6294968683
Revises: d2dcd3bc6f26
Create Date: 2025-12-19 16:11:13.276784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c6294968683'
down_revision: Union[str, None] = 'd2dcd3bc6f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risks',
    sa.Column('risk_id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('risk_description', sa.String(), nullable=False),
    sa.Column('risk_type', sa.String(), nullable=False),
    sa.Column('risk_level', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], ),
    sa.PrimaryKeyConstraint('risk_id', 'experiment_id')
    )
    op.create_table('decomissioning',
    sa.Column('decomissioning_id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('deployment_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('decomissioning_date', sa.Numeric(), nullable=False),
    sa.Column('decomissioning_actions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('procedure_details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id', 'deployment_id', 'model_id'], ['model_deployed.experiment_id', 'model_deployed.deployment_id', 'model_deployed.model_id'], ),
    sa.PrimaryKeyConstraint('decomissioning_id', 'experiment_id', 'deployment_id', 'model_id')
    )
    op.add_column('build_and_integration_testing', sa.Column('experiment_id', sa.String(), nullable=False))
    op.add_column('build_and_integration_testing', sa.Column('deployment_id', sa.String(), nullable=False))
    op.add_column('build_and_integration_testing', sa.Column('model_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('build_and_integration_testing_run_id_fkey'), 'build_and_integration_testing', type_='foreignkey')
    op.create_foreign_key(None, 'build_and_integration_testing', 'model_deployed', ['experiment_id', 'deployment_id', 'model_id'], ['experiment_id', 'deployment_id', 'model_id'])
    op.drop_column('build_and_integration_testing', 'run_id')
    op.add_column('data', sa.Column('data_acquisition_method', sa.String(), nullable=True))
    op.add_column('data_techniques', sa.Column('data_technique_stage', sa.String(), nullable=True))
    op.drop_column('data_techniques', 'value')
    op.add_column('declaration_of_conformity', sa.Column('link_to_artifacts', sa.String(), nullable=True))
    op.drop_column('declaration_of_conformity', 'loid')
    op.add_column('interfaces', sa.Column('experiment_id', sa.String(), nullable=False))
    op.add_column('interfaces', sa.Column('deployment_id', sa.String(), nullable=False))
    op.add_column('interfaces', sa.Column('model_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('interfaces_experiments_id_fkey'), 'interfaces', type_='foreignkey')
    op.create_foreign_key(None, 'interfaces', 'model_deployed', ['experiment_id', 'deployment_id', 'model_id'], ['experiment_id', 'deployment_id', 'model_id'])
    op.drop_column('interfaces', 'experiments_id')
    op.add_column('model_architecture', sa.Column('model_version', sa.Integer(), nullable=False))
    op.add_column('model_packaging', sa.Column('experiment_id', sa.String(), nullable=False))
    op.add_column('model_packaging', sa.Column('deployment_id', sa.String(), nullable=False))
    op.add_column('model_packaging', sa.Column('model_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('model_packaging_run_id_fkey'), 'model_packaging', type_='foreignkey')
    op.create_foreign_key(None, 'model_packaging', 'model_deployed', ['experiment_id', 'deployment_id', 'model_id'], ['experiment_id', 'deployment_id', 'model_id'])
    op.drop_column('model_packaging', 'run_id')
    op.add_column('standards', sa.Column('experiment_id', sa.String(), nullable=False))
    op.add_column('standards', sa.Column('deployment_id', sa.String(), nullable=False))
    op.add_column('standards', sa.Column('model_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('standards_experiments_id_fkey'), 'standards', type_='foreignkey')
    op.create_foreign_key(None, 'standards', 'model_deployed', ['experiment_id', 'deployment_id', 'model_id'], ['experiment_id', 'deployment_id', 'model_id'])
    op.drop_column('standards', 'experiments_id')
    op.add_column('visual_documentation', sa.Column('link_to_artifacts', sa.String(), nullable=True))
    op.drop_column('visual_documentation', 'height')
    op.drop_column('visual_documentation', 'width')
    op.drop_column('visual_documentation', 'mime_type')
    op.drop_column('visual_documentation', 'loid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visual_documentation', sa.Column('loid', postgresql.OID(), autoincrement=False, nullable=False))
    op.add_column('visual_documentation', sa.Column('mime_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('visual_documentation', sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('visual_documentation', sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('visual_documentation', 'link_to_artifacts')
    op.add_column('standards', sa.Column('experiments_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'standards', type_='foreignkey')
    op.create_foreign_key(op.f('standards_experiments_id_fkey'), 'standards', 'experiments', ['experiments_id'], ['experiment_id'])
    op.drop_column('standards', 'model_id')
    op.drop_column('standards', 'deployment_id')
    op.drop_column('standards', 'experiment_id')
    op.add_column('model_packaging', sa.Column('run_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'model_packaging', type_='foreignkey')
    op.create_foreign_key(op.f('model_packaging_run_id_fkey'), 'model_packaging', 'runs', ['run_id'], ['run_id'])
    op.drop_column('model_packaging', 'model_id')
    op.drop_column('model_packaging', 'deployment_id')
    op.drop_column('model_packaging', 'experiment_id')
    op.drop_column('model_architecture', 'model_version')
    op.add_column('interfaces', sa.Column('experiments_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'interfaces', type_='foreignkey')
    op.create_foreign_key(op.f('interfaces_experiments_id_fkey'), 'interfaces', 'experiments', ['experiments_id'], ['experiment_id'])
    op.drop_column('interfaces', 'model_id')
    op.drop_column('interfaces', 'deployment_id')
    op.drop_column('interfaces', 'experiment_id')
    op.add_column('declaration_of_conformity', sa.Column('loid', postgresql.OID(), autoincrement=False, nullable=False))
    op.drop_column('declaration_of_conformity', 'link_to_artifacts')
    op.add_column('data_techniques', sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('data_techniques', 'data_technique_stage')
    op.drop_column('data', 'data_acquisition_method')
    op.add_column('build_and_integration_testing', sa.Column('run_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'build_and_integration_testing', type_='foreignkey')
    op.create_foreign_key(op.f('build_and_integration_testing_run_id_fkey'), 'build_and_integration_testing', 'runs', ['run_id'], ['run_id'])
    op.drop_column('build_and_integration_testing', 'model_id')
    op.drop_column('build_and_integration_testing', 'deployment_id')
    op.drop_column('build_and_integration_testing', 'experiment_id')
    op.drop_table('decomissioning')
    op.drop_table('risks')
    # ### end Alembic commands ###
