"""update human_oversight_mechanism

Revision ID: 8472582eb58f
Revises: 6ce70ae22ea9
Create Date: 2026-08-18 16:02:40.969074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8472582eb58f'
down_revision: Union[str, None] = '6ce70ae22ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('human_oversight_mechanisms', sa.Column('run_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'human_oversight_mechanisms', 'runs', ['run_id'], ['run_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'human_oversight_mechanisms', type_='foreignkey')
    op.drop_column('human_oversight_mechanisms', 'run_id')
    # ### end Alembic commands ###
