"""Fix timestamp default values

Revision ID: 863097e14f7c
Revises: b5d680f9fa95
Create Date: 2025-04-29 16:03:56.077186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '863097e14f7c'
down_revision: Union[str, None] = 'b5d680f9fa95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runs', 'start_time',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('runs', 'end_time',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runs', 'end_time',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('runs', 'start_time',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
