"""Add DataSignatures

Revision ID: 8edb170261bf
Revises: c6237a40a767
Create Date: 2025-06-10 12:00:35.296777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8edb170261bf'
down_revision: Union[str, None] = 'c6237a40a767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_signatures',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('data_id', sa.String(), nullable=False),
    sa.Column('signature', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id', 'data_id'], ['data.run_id', 'data.data_id'], ),
    sa.PrimaryKeyConstraint('run_id', 'data_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_signatures')
    # ### end Alembic commands ###
