"""Fix the runCode nullable values table adding some more info

Revision ID: 97ea440db74e
Revises: 6a55889a3f39
Create Date: 2026-06-30 10:10:17.461619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ea440db74e'
down_revision: Union[str, None] = '6a55889a3f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runs_code', 'git_commit_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('runs_code', 'git_commit_short',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('runs_code', 'git_branch',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('runs_code', 'git_message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('runs_code', 'git_author',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('runs_code', 'git_author_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runs_code', 'git_author_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('runs_code', 'git_author',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('runs_code', 'git_message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('runs_code', 'git_branch',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('runs_code', 'git_commit_short',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('runs_code', 'git_commit_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
