"""Init database schema

Revision ID: b5d680f9fa95
Revises: 
Create Date: 2025-04-29 15:51:26.642475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5d680f9fa95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('experiment_name', sa.String(), nullable=False),
    sa.Column('lifecycle_stage', sa.String(), nullable=False),
    sa.Column('creation_time', sa.BigInteger(), nullable=False),
    sa.Column('last_update_time', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('experiment_id')
    )
    op.create_table('experiments_tags',
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], ),
    sa.PrimaryKeyConstraint('experiment_id', 'key')
    )
    op.create_table('runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('run_name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_time', sa.BigInteger(), nullable=False),
    sa.Column('end_time', sa.BigInteger(), nullable=False),
    sa.Column('source_version', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('data',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('data_id', sa.String(), nullable=False),
    sa.Column('data_stage', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('data_source', sa.String(), nullable=False),
    sa.Column('data_version', sa.String(), nullable=False),
    sa.Column('data_location', sa.String(), nullable=False),
    sa.Column('data_size', sa.Integer(), nullable=False),
    sa.Column('data_format', sa.String(), nullable=False),
    sa.Column('creation_time', sa.BigInteger(), nullable=False),
    sa.Column('last_update_time', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('run_id', 'data_id')
    )
    op.create_table('model_architecture',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('architecture_name', sa.String(), nullable=False),
    sa.Column('activation_function', sa.String(), nullable=False),
    sa.Column('loss_function', sa.String(), nullable=False),
    sa.Column('optimizer', sa.String(), nullable=False),
    sa.Column('layer_structure', sa.JSON(), nullable=False),
    sa.Column('framework', sa.String(), nullable=False),
    sa.Column('metrics', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('input_shape', sa.String(), nullable=False),
    sa.Column('output_shape', sa.String(), nullable=False),
    sa.Column('number_of_layers', sa.Integer(), nullable=False),
    sa.Column('number_of_total_parameters', sa.Integer(), nullable=False),
    sa.Column('number_of_trainable_parameters', sa.Integer(), nullable=False),
    sa.Column('nummber_of_non_trainable_parameters', sa.Integer(), nullable=False),
    sa.Column('creation_time', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('run_id', 'model_id')
    )
    op.create_table('model_deployed',
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('deployment_id', sa.String(), nullable=False),
    sa.Column('deployed_time', sa.BigInteger(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('model_format', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('experiment_id', 'model_id', 'deployment_id')
    )
    op.create_table('runs_code',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('git_commit_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('runs_logs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('log_type', sa.String(), nullable=False),
    sa.Column('log_message', sa.String(), nullable=False),
    sa.Column('log_creation_time', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('run_id', 'log_id')
    )
    op.create_table('runs_tags',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('run_id', 'key')
    )
    op.create_table('checkpoints',
    sa.Column('checkpoint_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('checkpoint_name', sa.String(), nullable=False),
    sa.Column('checkpoint_location', sa.String(), nullable=False),
    sa.Column('creation_time', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['run_id', 'model_id'], ['model_architecture.run_id', 'model_architecture.model_id'], ),
    sa.PrimaryKeyConstraint('run_id', 'checkpoint_id', 'model_id')
    )
    op.create_table('data_hyperparameters',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('data_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('technical_name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id', 'data_id'], ['data.run_id', 'data.data_id'], ),
    sa.PrimaryKeyConstraint('run_id', 'data_id', 'key', 'technical_name')
    )
    op.create_table('data_metrics',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('data_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('data_stage', sa.String(), nullable=False),
    sa.Column('is_NaN', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id', 'data_id'], ['data.run_id', 'data.data_id'], ),
    sa.PrimaryKeyConstraint('run_id', 'data_id', 'key')
    )
    op.create_table('data_resources',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('data_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['run_id', 'data_id'], ['data.run_id', 'data.data_id'], ),
    sa.PrimaryKeyConstraint('run_id', 'data_id', 'key')
    )
    op.create_table('data_techniques',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('data_id', sa.String(), nullable=False),
    sa.Column('technique_name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id', 'data_id'], ['data.run_id', 'data.data_id'], ),
    sa.PrimaryKeyConstraint('run_id', 'data_id', 'technique_name')
    )
    op.create_table('drift_metrics',
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('deployment_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id', 'deployment_id', 'model_id'], ['model_deployed.experiment_id', 'model_deployed.deployment_id', 'model_deployed.model_id'], ),
    sa.PrimaryKeyConstraint('experiment_id', 'deployment_id', 'model_id', 'value', 'timestamp')
    )
    op.create_table('examples',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('input', sa.String(), nullable=False),
    sa.Column('prediction', sa.String(), nullable=False),
    sa.Column('ground_truth', sa.String(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['run_id', 'model_id'], ['model_architecture.run_id', 'model_architecture.model_id'], ),
    sa.PrimaryKeyConstraint('run_id', 'model_id', 'input', 'prediction', 'ground_truth', 'step', 'stage', 'timestamp')
    )
    op.create_table('last_model_metrics',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('is_NaN', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['run_id', 'model_id'], ['model_architecture.run_id', 'model_architecture.model_id'], ),
    sa.PrimaryKeyConstraint('run_id', 'key', 'model_id')
    )
    op.create_table('model_hyperparameters',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id', 'model_id'], ['model_architecture.run_id', 'model_architecture.model_id'], ),
    sa.PrimaryKeyConstraint('run_id', 'key', 'model_id')
    )
    op.create_table('model_metrics',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('is_NaN', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['run_id', 'model_id'], ['model_architecture.run_id', 'model_architecture.model_id'], ),
    sa.PrimaryKeyConstraint('run_id', 'key', 'model_id', 'step', 'stage', 'timestamp', 'is_NaN', 'value')
    )
    op.create_table('monitor_logs',
    sa.Column('deployment_id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id', 'deployment_id', 'model_id'], ['model_deployed.experiment_id', 'model_deployed.deployment_id', 'model_deployed.model_id'], ),
    sa.PrimaryKeyConstraint('deployment_id', 'experiment_id', 'model_id', 'log_id')
    )
    op.create_table('resources',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['run_id', 'model_id'], ['model_architecture.run_id', 'model_architecture.model_id'], ),
    sa.PrimaryKeyConstraint('run_id', 'key', 'model_id', 'value', 'stage', 'timestamp', 'step')
    )
    op.create_table('runtime_environment',
    sa.Column('deployment_id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('server_name', sa.String(), nullable=True),
    sa.Column('performance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id', 'deployment_id', 'model_id'], ['model_deployed.experiment_id', 'model_deployed.deployment_id', 'model_deployed.model_id'], ),
    sa.PrimaryKeyConstraint('deployment_id', 'experiment_id', 'model_id')
    )
    op.create_table('weight_distribution',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('layer_name', sa.String(), nullable=False),
    sa.Column('std', sa.Integer(), nullable=False),
    sa.Column('mean', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('is_NaN', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['run_id', 'model_id'], ['model_architecture.run_id', 'model_architecture.model_id'], ),
    sa.PrimaryKeyConstraint('run_id', 'layer_name', 'model_id', 'step', 'stage', 'timestamp', 'is_NaN', 'mean', 'std')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weight_distribution')
    op.drop_table('runtime_environment')
    op.drop_table('resources')
    op.drop_table('monitor_logs')
    op.drop_table('model_metrics')
    op.drop_table('model_hyperparameters')
    op.drop_table('last_model_metrics')
    op.drop_table('examples')
    op.drop_table('drift_metrics')
    op.drop_table('data_techniques')
    op.drop_table('data_resources')
    op.drop_table('data_metrics')
    op.drop_table('data_hyperparameters')
    op.drop_table('checkpoints')
    op.drop_table('runs_tags')
    op.drop_table('runs_logs')
    op.drop_table('runs_code')
    op.drop_table('model_deployed')
    op.drop_table('model_architecture')
    op.drop_table('data')
    op.drop_table('runs')
    op.drop_table('experiments_tags')
    op.drop_table('experiments')
    # ### end Alembic commands ###
