"""update decomissioning table

Revision ID: c6ef07767135
Revises: 8472582eb58f
Create Date: 2026-08-19 10:46:57.191419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6ef07767135'
down_revision: Union[str, None] = '8472582eb58f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decomissioning', sa.Column('system_name', sa.String(), nullable=True))
    op.add_column('decomissioning', sa.Column('decommissioning_plan', sa.String(), nullable=True))
    op.add_column('decomissioning', sa.Column('approvals', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('decomissioning', sa.Column('data_retention_archive', sa.String(), nullable=True))
    op.add_column('decomissioning', sa.Column('migration', sa.String(), nullable=True))
    op.add_column('decomissioning', sa.Column('access_removal', sa.String(), nullable=True))
    op.add_column('decomissioning', sa.Column('infrastructure_shutdown', sa.String(), nullable=True))
    op.add_column('decomissioning', sa.Column('evidence_documentation', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('decomissioning', sa.Column('audit_trail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decomissioning', 'audit_trail')
    op.drop_column('decomissioning', 'evidence_documentation')
    op.drop_column('decomissioning', 'infrastructure_shutdown')
    op.drop_column('decomissioning', 'access_removal')
    op.drop_column('decomissioning', 'migration')
    op.drop_column('decomissioning', 'data_retention_archive')
    op.drop_column('decomissioning', 'approvals')
    op.drop_column('decomissioning', 'decommissioning_plan')
    op.drop_column('decomissioning', 'system_name')
    # ### end Alembic commands ###
