"""add tables for the unmapped values

Revision ID: d2dcd3bc6f26
Revises: 34854eb80257
Create Date: 2025-12-19 00:23:16.878152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2dcd3bc6f26'
down_revision: Union[str, None] = '34854eb80257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_actors',
    sa.Column('ai_actors_id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('ai_provider', sa.String(), nullable=True),
    sa.Column('ai_deployer', sa.String(), nullable=True),
    sa.Column('auditor', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], ),
    sa.PrimaryKeyConstraint('ai_actors_id', 'experiment_id')
    )
    op.create_table('human_oversight_mechanisms',
    sa.Column('mechanism_id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('oversight_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('implementation_details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], ),
    sa.PrimaryKeyConstraint('mechanism_id', 'experiment_id')
    )
    op.create_table('interfaces',
    sa.Column('interface_id', sa.String(), nullable=False),
    sa.Column('experiments_id', sa.String(), nullable=False),
    sa.Column('interface_type', sa.String(), nullable=False),
    sa.Column('specifications', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('documentation_link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['experiments_id'], ['experiments.experiment_id'], ),
    sa.PrimaryKeyConstraint('interface_id', 'experiments_id')
    )
    op.create_table('labeling_procedures',
    sa.Column('labeling_id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('procedure_description', sa.String(), nullable=True),
    sa.Column('quality_assurance_methods', sa.String(), nullable=True),
    sa.Column('annotator_details', sa.String(), nullable=True),
    sa.Column('annotation_tools', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], ),
    sa.PrimaryKeyConstraint('labeling_id', 'experiment_id')
    )
    op.create_table('standards',
    sa.Column('standard_id', sa.String(), nullable=False),
    sa.Column('experiments_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('publication_date', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['experiments_id'], ['experiments.experiment_id'], ),
    sa.PrimaryKeyConstraint('standard_id', 'experiments_id')
    )
    op.create_table('transparency_measures',
    sa.Column('measure_id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('measure_type', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('measure_value', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('implementation_details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], ),
    sa.PrimaryKeyConstraint('measure_id', 'experiment_id')
    )
    op.create_table('build_and_integration_testing',
    sa.Column('test_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('build_status', sa.String(), nullable=True),
    sa.Column('build_logs', sa.String(), nullable=True),
    sa.Column('build_timestamp', sa.Numeric(), nullable=False),
    sa.Column('test_type', sa.String(), nullable=True),
    sa.Column('test_results', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('test_id', 'run_id')
    )
    op.create_table('declaration_of_conformity',
    sa.Column('declaration_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('loid', postgresql.OID(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('creation_time', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('declaration_id', 'run_id')
    )
    op.create_table('explainable_ai_features',
    sa.Column('feature_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('feature_name', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('feature_values', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('implementation_details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('feature_id', 'run_id')
    )
    op.create_table('model_packaging',
    sa.Column('packaging_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('packaging_format', sa.String(), nullable=True),
    sa.Column('dependencies', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('containerization_details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('packaging_id', 'run_id')
    )
    op.create_table('visual_documentation',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('loid', postgresql.OID(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('creation_time', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('document_id', 'run_id')
    )
    op.add_column('data_hyperparameters', sa.Column('technique_name', sa.String(), nullable=False))
    op.add_column('data_hyperparameters', sa.Column('technique_parameter_name', sa.String(), nullable=False))
    op.add_column('data_hyperparameters', sa.Column('technique_parameter_value', sa.String(), nullable=False))
    op.drop_column('data_hyperparameters', 'technical_name')
    op.drop_column('data_hyperparameters', 'key')
    op.add_column('experiments', sa.Column('description', sa.String(), nullable=True))
    op.add_column('model_architecture', sa.Column('number_of_non_trainable_parameters', sa.Integer(), nullable=True))
    op.drop_column('model_architecture', 'nummber_of_non_trainable_parameters')
    op.add_column('model_deployed', sa.Column('model_cateory', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_deployed', 'model_cateory')
    op.add_column('model_architecture', sa.Column('nummber_of_non_trainable_parameters', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('model_architecture', 'number_of_non_trainable_parameters')
    op.drop_column('experiments', 'description')
    op.add_column('data_hyperparameters', sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('data_hyperparameters', sa.Column('technical_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('data_hyperparameters', 'technique_parameter_value')
    op.drop_column('data_hyperparameters', 'technique_parameter_name')
    op.drop_column('data_hyperparameters', 'technique_name')
    op.drop_table('visual_documentation')
    op.drop_table('model_packaging')
    op.drop_table('explainable_ai_features')
    op.drop_table('declaration_of_conformity')
    op.drop_table('build_and_integration_testing')
    op.drop_table('transparency_measures')
    op.drop_table('standards')
    op.drop_table('labeling_procedures')
    op.drop_table('interfaces')
    op.drop_table('human_oversight_mechanisms')
    op.drop_table('ai_actors')
    # ### end Alembic commands ###
