"""update standard database table, fix names

Revision ID: f2eacbdb30d4
Revises: 63b26ad2ae62
Create Date: 2026-08-14 16:54:10.081071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2eacbdb30d4'
down_revision: Union[str, None] = '63b26ad2ae62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standards', sa.Column('name', sa.String(), nullable=False))
    op.add_column('standards', sa.Column('publication_date', sa.Integer(), nullable=True))
    op.add_column('standards', sa.Column('model_id', sa.String(), nullable=True))
    op.alter_column('standards', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('standards', 'version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('standards', 'link_to_artifacts')
    op.drop_column('standards', 'filename')
    op.drop_column('standards', 'mime_type')
    op.drop_column('standards', 'file_size')
    op.drop_column('standards', 'file_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standards', sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('standards', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('standards', sa.Column('mime_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('standards', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('standards', sa.Column('link_to_artifacts', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('standards', 'version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('standards', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('standards', 'model_id')
    op.drop_column('standards', 'publication_date')
    op.drop_column('standards', 'name')
    # ### end Alembic commands ###
